[package]
name = "some-auth"
version = "0.0.1"
edition = "2021"
authors = ["shurikeagle <alexander.orlov22@gmail.com>"]
repository = "https://github.com/shurikeagle/some-auth.git"
license = "MIT"
keywords = ["jwt", "auth", "authentication", "async auth"]

[dependencies]
