[package]
name = "some-auth"
version = "0.0.3"
edition = "2021"
authors = ["shurikeagle <alexander.orlov22@gmail.com>"]
repository = "https://github.com/shurikeagle/some-auth.git"
license = "MIT"
keywords = ["jwt", "auth", "authentication", "async auth"]

[dependencies]
async-trait = "0.1.81"
bcrypt = "0.15.1"
chrono = "0.4.38"
hex = "0.4.3"
jsonwebtoken = "9.3.0"
regex = "1.10.5"
serde = "1.0.204"
sha2 = "0.10.8"
